apiVersion: vappcontainer.vsphere.upbound.io/v1alpha1
kind: Container
metadata:
  annotations:
    meta.upbound.io/example-id: vappcontainer/v1alpha1/container
  labels:
    testing.upbound.io/example-name: vapp_container
  name: vapp-container
spec:
  forProvider:
    name: vapp-01
    parentResourcePoolId: resgroup-291
  providerConfigRef:
    name: vsphere-provider
---

