apiVersion: computeclustervmgroup.vsphere.upbound.io/v1alpha1
kind: ClusterVMGroup
metadata:
  annotations:
    meta.upbound.io/example-id: computeclustervmgroup/v1alpha1/clustervmgroup
  labels:
    testing.upbound.io/example-name: cluster_vm_group
  name: cluster-vm-group
spec:
  forProvider:
    computeClusterId: ${data.vsphere_compute_cluster.cluster.id}
    name: terraform-test-cluster-vm-group
    virtualMachineIds:
    - ${vsphere_virtual_machine.vm.*.id}

---

apiVersion: virtualmachine.vsphere.upbound.io/v1alpha1
kind: Machine
metadata:
  annotations:
    meta.upbound.io/example-id: computeclustervmgroup/v1alpha1/clustervmgroup
  labels:
    testing.upbound.io/example-name: vm
  name: vm
spec:
  forProvider:
    count: 2
    datastoreId: ${data.vsphere_datastore.datastore.id}
    disk:
    - label: disk0
      size: 20
    guestId: other3xLinux64Guest
    memory: 2048
    networkInterface:
    - networkId: ${data.vsphere_network.network.id}
    numCpus: 2
    resourcePoolId: ${data.vsphere_compute_cluster.cluster.resource_pool_id}

---

