apiVersion: computecluster.vsphere.upbound.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: computecluster/v1alpha1/cluster
    crossplane.io/external-name: domain-c290
  labels:
    testing.upbound.io/example-name: cluster01
  name: cluster01
spec:
  forProvider:
    datacenterId: datacenter-18
    #drsEnabled: false
    #haEnabled: false
    #vsanEnabled: false
    hostSystemIds:
    name: Cluster01
  providerConfigRef:
    name: vsphere-provider
---

