apiVersion: resourcepool.vsphere.upbound.io/v1alpha1
kind: Pool
metadata:
  annotations:
    meta.upbound.io/example-id: resourcepool/v1alpha1/pool
  labels:
    testing.upbound.io/example-name: resource_pool
  name: resource-pool
spec:
  forProvider:
    name: resource-pool
    parentResourcePoolId: resgroup-291
  providerConfigRef:
    name: vsphere-provider
---
